query FetchGaugeShares($gaugeAddress: String!, $block: Int) {
  gaugeShares(
    block: { number: $block }
    where: { gauge_contains_nocase: $gaugeAddress, balance_gt: "0" }
    orderBy: balance
    orderDirection: desc
    first: 1000
  ) {
    balance
    id
    user {
      id
    }
  }
}
