query ExaminePoolLiquidProtocolYieldFee($poolId: String!) {
  pools(where: { id: $poolId }) {
    symbol
    priceRateProviders {
      address
    }
    totalLiquidity
    protocolYieldFeeCache
    swapFee
    poolType
    poolTypeVersion
  }
}
