query GetBalancerPool($id: ID!, $block: Int) {
    pool(id: $id, block: {number: $block}){
        id
    address
    poolType
    symbol
    name
    swapFee
    totalWeight
    totalSwapVolume
    totalSwapFee
    totalLiquidity
    totalProtocolFee
    totalShares
    swapsCount
    holdersCount
    createTime
    owner
    amp
    factory
    strategyType
    swapEnabled
    tokens(first: 10) {
        id
    symbol
    name
    decimals
    address
    balance
    weight
    priceRate
    poolId {
        id
        address
    }
    }
    }
}