query GetUserPoolBalances($poolId: ID!, $block: Int) {
  pool(id: $poolId, block: { number: $block }) {
    shares(where: { balance_gt: "0" }, orderBy: balance, orderDirection: desc) {
      userAddress {
        id
      }
      balance
    }
  }
}
