query LastJoinExit($poolId: String!) {
  joinExits(first: 1, orderBy: timestamp, orderDirection: desc, where: {pool: $poolId}) {
        amounts
    valueUSD
    id
    sender
    timestamp
    tx
    type
    pool {
        id
        tokensList
    }
    }
}