name: Lint
permissions:
  contents: write

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Black
        uses: psf/black@stable
        with:
          options: "--verbose"
          version: "24.4.0"

      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v7.0.0
        with:
          commit_message: "style: ci lint with `black`"
