name: Generate Active Permissions

on:
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:

jobs:
  refresh_active_perms:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    env:
      DRPC_KEY: ${{ secrets.DRPC_KEY }}
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Update Files
        id: update
        run: |
          pip3 install -r bal_addresses/requirements.txt
          python3 gen_current_permissions.py
          git add -A

      - name: pull-request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "Scheduled update to active permissions"
          title: "Scheduled update to active permissions"
          branch: "gha-permissions"
          reviewers: "gosuto-inzasheru"
          labels: "Automatic"

      - name: Enable auto-merge
        if: steps.create-pr.outputs.pull-request-number
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh pr merge --auto --merge ${{ steps.create-pr.outputs.pull-request-number }}
